### PR TITLE
Issue 107 committee page frontend fixes

### LINKED ISSUE #107: committee page frontend fixes
fixes:
- increase size of font for photo frame labels
  - may need to slightly increase size of photo frames and committee pictures to facilitate this
- increase space between footer and bottom row of photo frames
- make committee names/photos clickable - should take you to the relevant committee page

### PR DESCRIPTION
**Pull request by Games4Doritos**
## Change Summary
-Increased the font size of the committee portrait labels to md
- Increased the sizes of the committee frames and photos to accomodate this larger font size, whilst maintaining the same photo width : frame width and photo height : frame height ratios, rounded to one decimal place (see commit history for exact values)
- Increased bottom padding of the committee section as requested
- To be able to put Links to the committee's member pages on their photos and names in the about page, the member serializer was updated to include the "pk" field (the member's integer id). This field will now be fetched as well on the about page, and will complete the link to each committee member's member page. This field as been added to all other instances of fetching a member in the codebase, though only used for this page. 
- Conditional rendering has been implemented in the about page, where committee member's page links will only render if they have a valid id (0 is the placeholder and is invalid, as id's start at 1)

image

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [x] The change has documentation

## Other Information

# Related issue

- Resolve #107

### CODE REVIEW

File: client/src/pages/about.tsx [hunk 1]
```diff
@@ -61,6 +62,18 @@ export default function AboutPage() {
...
 
+  function committeeImage(profilePic: string) {
+    return (
+      <Image
+        src={profilePic === null ? "/landing_placeholder.png" : profilePic}
+        alt="/landing_placeholder.png"
+        width={134}
+        height={144}
+        className="h-[9rem] w-[8.4rem]"
+      />
```
Comment (laurenpudz) [inline client/src/pages/about.tsx]: just noticed that images are not maintaining aspect ratio here and becoming warped

Image

File: client/src/pages/about.tsx [hunk 2]
```diff
@@ -118,22 +133,23 @@ export default function AboutPage() {
...
-                <div className="w-[11.25rem] pl-3 text-left font-firaCode text-[0.5rem] leading-tight">
+                <div className="w-56 pl-3 text-left font-firaCode text-sm leading-tight">
                   <p className="inline-block bg-card px-2 py-1 text-white">
-                    {member.name} {member.pronouns}
+                    {member.pk === 0 ? (
+                      <>{member.name}</>
+                    ) : (
+                      <Link href={`/members/${member.pk}`}>{member.name}</Link>
+                    )}
+                    {member.pronouns}
```
Comment (laurenpudz) [inline client/src/pages/about.tsx]: can we refactor this out into a component instead of repeating it twice?

**Review by laurenpudz — CHANGES_REQUESTED** [review]

File: client/src/pages/about.tsx (hunk 1 above)
Comment (Games4Doritos) [reply client/src/pages/about.tsx]: I think the warping happens because the width and height props are not equal to the width and height set in tailwind? Doing some research, those props represent the intrinsic image size, but the height and width set in CSS determine what size the image should stretch to fit I think?
